-
  executer:
    name: exec
    param:
      exec: 'export PORT;cd /tmp/ && python -m SimpleHTTPServer $PORT'
  scheduler:
    envhard: 'arch=x86_64,os=Linux'
    envsoft: 'app1=1.0'
    count: 5
    resources:
      - [ 'CPU', '.', 2 ] 
      - [ 'PORT', '.', 1 ]
  ingress:
    domain: foo.com
    location: /
-
  executer:
    name: exec
    param:
      exec: 'export PORT;cd /tmp/ && python -m SimpleHTTPServer $PORT'
  scheduler:
    envhard: 'arch=x86_64,os=Linux'
    envsoft: 'app1=1.0'
    count: 5
    resources:
      - [ 'CPU', '.', 2 ] 
      - [ 'PORT', '.', 1 ]
  ingress:
    domain: foo.com
    location: /abc/
