#!# perl: code/
use warnings;
use strict;

=head3 return

  return 
    ID1: values1
    ID2: values3

    or 

    value

=cut

my ( $time, $r ) = ( 0 );

return sub
{
    my $t = time;

    return $r if time - $time < 10;
    my @df = `LANG=en df -l`;
    chomp @df;
    my ( $total, $use ) = ( 1, 1 );
    for my $df ( @df )
    {
        next unless $df =~ /^\/dev\//;
        my @x = split /\s+/, $df;
        $total += $x[1];
        $use += $x[2];
    }

    $time = $t;
    return $r = sprintf "%0.2f", 100 * $use / $total;
};
