#!# perl: code/
use warnings;
use strict;

=head3 return

  return 
    ID1: values1
    ID2: values3

    or 

    value

=cut

my $nogpu = 1;

return sub
{
    return unless $nogpu;
    $nogpu = 0 unless -e '/dev/nvidia0';

    my ( @info, %x ) = `tail -n 20 /opt/AntDen/logs/nvidia-smi.log`;

    map{
        my @x = split /\s+/, $_;
        $x{$x[1]} = $x[2] if $x[1] =~ /^\d+$/;
    } @info;

    return \%x;
};
