#!# perl: code/
use warnings;
use strict;

=head3 return

  return 
    ID1: values1
    ID2: values3

    or 
    
    value

=cut

return sub
{
    return `LANG=en uptime` =~ /load average: ([0-9\.]+)/ ? $1 : -1;
};
