#!# perl: code/
use warnings;
use strict;

=head3 return

  return 
    ID1: values1
    ID2: values3

    or 
    
    value

=cut

return sub
{
    my $meminfo = `cat /proc/meminfo`;
    die "get mem fail" unless `cat /proc/meminfo | grep MemTotal` =~ /MemTotal:[\D]*(\d+)[\D]*kB/;
    my $MemTotal = $meminfo =~ /\bMemTotal:[\D]*(\d+)[\D]*kB/ ? $1 : -1;

    my $free;
    if( $meminfo =~ /MemAvailable:[\D]*(\d+)[\D]*kB/ )
    {
        $free = $1;
    }
    else
    {
        map{ 
            $free += $1 if $meminfo =~ /\b$_:[\D]*(\d+)[\D]*kB/;
        }qw( MemFree Buffers Cached );
    }
    return int( ( $MemTotal - $free ) / 1024 );
};
