#!# perl: code/
use warnings;
use strict;

=head3 param

  cmd: /bin/bash
  image: ubuntu

=cut

return sub
{
    my $param = shift @_;

    die "cmd undef" unless defined $param->{cmd};
    die "Cannot use the --name in cmd\n" if $param->{cmd} =~ / --name /;
    die "image undef" unless $param->{image};

    return;
};
