#!# perl: code/
use warnings;
use strict;

use YAML::XS;

=head3 param

  param:
    executeid

=head3 return

  return status, running or stoped

=cut

return sub
{
    my $param = shift @_;

    my $x = `docker inspect $param->{executeid}`;
    my $c = eval{ YAML::XS::Load $x };
    die "load docker.inspect fail: $@\n" if $@;
    die "nofind container status\n" unless $c && ref $c eq 'ARRAY';

    if( @$c )
    {
        die "nofind container status in docker.inspect.State.Status\n"
            unless $c->[0]->{State} && $c->[0]->{State}{Status};
        return $c->[0]->{State}{Status} eq 'running' ? 'running' : 'stoped';
    }
    else
    {
        return ( system "killall -0 $param->{executeid}" ) ? 'stoped' : 'running';
    }
};
