#!# perl: code/
use warnings;
use strict;

=head3 param

  param:
    executeid

=head3 return

  return null

=cut

return sub
{
    my $param = shift @_;

    if( $param->{stopcount} && $param->{stopcount} > 5 )
    {
        system "killall -KILL $param->{executeid}";
        system "docker kill $param->{executeid}";
    }
    else
    {
        system "killall -TERM $param->{executeid}";
        system "docker stop $param->{executeid}";
    }

    return;
};
