#!# perl: code/
use warnings;
use strict;

=head3 param

  param:
    executeid

=head3 return

  return null

=cut

return sub
{
    my $param = shift @_;

    my $kill = $param->{stopcount} > 5 ? 'kill' : 'stop';
    system "docker $kill $param->{executeid}";

    return;
};
