#!# perl: code/
use warnings;
use strict;

=head3 param

  param:
    executeid

=head3 return

  return status, running or stoped

=cut

return sub
{
    my $param = shift @_;

    return kill( 0, $param->{executeid} ) ? 'running' : 'stoped';
};
