#!/opt/mydan/perl/bin/perl -I/opt/AntDen/lib
use strict;
use warnings;
use AntDen;
use FindBin qw( $RealBin );
use YAML::XS;
use MYDan;

=head1 SYNOPSIS

 $0

=cut

if( my @x = `ps -ef|grep [A]ntDen_dashboard_`  )
{
    print @x;
    die "Err: Already running!\n";
}

die "start $_ fail: $!" if system "$MYDan::PATH/dan/tools/supervisor --name AntDen_dashboard_supervisor --cmd '$AntDen::PATH/dashboard/bin/app.pl  --port=3000 --confdir=$AntDen::PATH/dashboard/config' --log '$AntDen::PATH/logs/dashboard'";
die "start $_ fail: $!" if system "$MYDan::PATH/dan/tools/supervisor --name AntDen_dashboard_supervisor.logws --cmd '/opt/mydan/perl/bin/twiggy $AntDen::PATH/dashboard/bin/app_logws.pl --port=3001 -I/opt/AntDen/lib' --log '$AntDen::PATH/logs/dashboard_logws'";

sleep 1;

print "Process:\n";
system "ps -ef|grep [A]ntDen_dashboard_";
system "lsof -i:3001";
