#This is AntDen Dockerfile#version 1.0
#Author: lijinfeng2011@gmail.com
#Base image 基础镜像

FROM centos:7
MAINTAINER lijinfeng2011

RUN yum -y install wget make rsync gcc lsof

ARG VERSION
RUN echo version:$VERSION

RUN curl -L update.mydan.org | MYDanInstallLatestVersion=1 bash

RUN mydan config agent.role=client

ADD https://github.com/AntDen/datasets/archive/latest.tar.gz /tmp/latest.tar.gz
RUN cd /tmp && tar -zxvf latest.tar.gz
RUN rsync -av /tmp/datasets-latest/ /opt/mydan/dan/antden/

ADD entrypoint.pl /
ENTRYPOINT [ "/entrypoint.pl" ]
