#!# perl: code/
use warnings;
use strict;

=head3 return

  return version or status

=cut

return sub
{
    #Disabled Enforcing Permissive Unkown
    my $status = `LANG=en getenforce 2>/dev/null`;
    chomp $status;
    $status = 'Unkown' unless $status && $status =~ /^[a-zA-Z]+$/;
    return $status;
};
