#!# perl: code/
use warnings;
use strict;

=head3 return

  return version or status

=cut

return sub
{
    my $version = `LANG=en nvidia-smi 2>/dev/null`;
    return ( $version && $version =~ /CUDA\s+Version:\s+([a-zA-Z0-9\.]+)\s*\|/ ) ? $1 : 'Unkown';
};
