#!# perl: code/
use warnings;
use strict;

=head3 param

  domain: acb.com
  location:
    /: [ '127.0.0.1:8080', '127.0.0.1:8081' ]
    /abc/: [ '127.0.0.1:8080' ]

=cut

return sub
{
    my $param = shift @_;

    map{ die "$_ undef" unless $param->{$_} }qw( location domain );
    die "location not array" unless ref $param->{location} eq 'HASH';

    return;
};
