#!# perl: code/
use warnings;
use strict;

=head3 param

  domain: acb.com
  upstream: [ '127.0.0.1:8080', '127.0.0.1:8081' ]

=cut

return sub
{
    my $param = shift @_;

    map{ die "$_ undef" unless $param->{$_} }qw( upstream domain );
    die "upstream not array" unless ref $param->{upstream} eq 'ARRAY';

    return;
};
