#!# perl: code/
use warnings;
use strict;

=head3 return

  return 
    [ ID1, values1 ]
    [ ID2: values2 ]

    or 
    
    value

=cut

return sub
{
    die "get cpu fail" unless `cat /proc/cpuinfo | grep "processor" | wc -l` =~ /(\d+)/;
    return int $1 * 1024;
};
