#!# perl: code/
use warnings;
use strict;

=head3 return

  return 
    [ ID1, values1 ]
    [ ID2: values2 ]

    or 
    
    value

=cut

return sub
{
    my @r;
    map{ push( @r, [ $1, 1 ] ) if $_ =~ /\/nvidia(\d+)$/ }glob "/dev/nvidia*";
    return \@r;
};
