#!# perl: code/
use warnings;
use strict;

=head3 return

  return 
    [ ID1, values1 ]
    [ ID2: values2 ]

    or 
    
    value

=cut

return sub
{
    die "get mem fail" unless `cat /proc/meminfo | grep MemTotal` =~ /MemTotal:[\D]*(\d+)[\D]*kB/;
    return int( $1 / 1024 );
};
