#!# perl: code/
use warnings;
use strict;

=head3 return

  return 
    [ ID1, values1 ]
    [ ID2: values2 ]

    or 
    
    value

=cut

return sub
{
    my %use;
    for( `LANG=en netstat -nlpt` )
    {
        $use{$1} = 1 if ( split /\s+/, $_ )[3] =~ /:(\d+)/;
    }
    return [ map{ [$_, 1] } grep{ !$use{$_}}65000 .. 65020];
};
